AuctionSystem/Controllers/AuctionCommentController.cs
using AuctionSystem.Core.Contracts;
using AuctionSystem.Core.Models.AuctionComment;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace AuctionSystem.Controllers
{
    public class AuctionCommentController : Controller
    {
        private readonly IAuctionCommentService auctionCommentService;

        public AuctionCommentController(IAuctionCommentService _auctionCommentService)
        {
            auctionCommentService = _auctionCommentService;
        }

        [HttpGet]
        public async Task<IActionResult> AllCommentsForAuction(int id)
        {
            if(await auctionCommentService.AuctionExistAsync(id)== false)
            {
                return BadRequest();
            }

            var model = await auctionCommentService.AllCommentsForAuctionAsync(id);

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AllAuctionCommentsFromUser(string id)
        {
            if (await auctionCommentService.UserExistAsync(id) == false)
            {
                return BadRequest();
            }

            var comments = await auctionCommentService.GetAllAuctionCommentsFromUser(id);

            return View(comments);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var model = new AuctionCommentFormViewModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AuctionCommentFormViewModel model)
        {
            if (await auctionCommentService.AuctionExistAsync(model.Id) == false)
            {
                ModelState.AddModelError(nameof(model.Id), "Auction does not exist");
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var userId = GetUserId();
            await auctionCommentService.AddAsync(model,userId);

            return RedirectToAction("All","Auction");
        }

        private string GetUserId()
        {
            var userId = ClaimsPrincipalExtensions.Id(this.User);
            return userId;
        }
    }
}

AuctionSystem/Controllers/AuctionController.cs
using AuctionSystem.Core.Contracts;
using AuctionSystem.Core.Models.Auction;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace AuctionSystem.Controllers
{
    public class AuctionController : BaseController
    {
        private readonly IAuctionService auctionService;

        public AuctionController(IAuctionService service)
        {
            auctionService = service;
        }

        [HttpGet]
        public async Task<IActionResult> All([FromQuery] AuctionQueryViewModel model)
        {
            var auctions = await auctionService.AllAuctionAsync(
                model.SearchTerm,
                model.Sorting,
                model.CurrentPage,
                model.AuctionPerPage);

            model.TotalAuctionCount = auctions.TotalAuctionCount;
            model.Auction = auctions.Auction;

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AllAuctionsForUser(string id)
        {
            if (await auctionService.UserExistAsync(id) == false)
            {
                return BadRequest();
            }

            var auctions = await auctionService.GetAllAuctionsForUser(id);

            return View(auctions);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            if (await auctionService.ExistAsync(id) == false)
            {
                return BadRequest();
            }

            var model = await auctionService.DetailsAuctionAsync(id);

            if(model.ConditionId == 4)
            {
                return View(model);
            }
            else
            {
                return BadRequest();
            }
        }
      
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            if(User.IsCustomer() == false)
            {
                return Unauthorized();
            }

            var model = new AuctionFormViewModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AuctionFormViewModel model, List<string> imageUrls)
        {
            if (!User.IsCustomer())
            {
                return Unauthorized();
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            string userId = GetUserId();

            int auctionId =  await auctionService.AddAsync(model, userId);
            var auction = await auctionService.GetAuctionByIdAsync(auctionId);

            await auctionService.AddImagesAsync(auction, model.Image, imageUrls);

            var days = auction.BiddingPeriodInDays;
            var endDate = auction.StartingAuctionDateTime.AddDays(days);

            ScheduleAuctionCompletion(auction.Id, endDate);

            return RedirectToAction(nameof(All));
        }

        private void ScheduleAuctionCompletion(int auctionId, DateTime endDate)
        {
            var delay = endDate - DateTime.Now;

            if (delay <= TimeSpan.Zero)
            {
                Task.Run(() => EndAuctionAfterTimeExpires(auctionId));
            }
            else
            {
                Task.Delay(delay).ContinueWith(_ => EndAuctionAfterTimeExpires(auctionId));
            }
        }
        private async Task EndAuctionAfterTimeExpires(int auctionId)
        {
            await auctionService.SetConditionToFinish(auctionId);
        }
        [HttpGet]
        public async Task<IActionResult> TerminateAuction(int id)
        {
            if (await auctionService.ExistAsync(id) == false)
            {
                return BadRequest();
            }

            var auction = await auctionService.GetAuctionByIdAsync(id);

            if(auction.ConditionId != 4)
            {
                return BadRequest();
            }

            string userId = GetUserId();

            if (User.IsCustomer() && userId == auction.SellerId)
            {
                await auctionService.TerminateAuction(auction.Id);
                return RedirectToAction(nameof(All));
            }
            else
            {
                return Unauthorized();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (await auctionService.ExistAsync(id) == false)
            {
                return BadRequest();
            }

            var auction = await auctionService.GetAuctionByIdAsync(id);
            string userId = GetUserId();

            if (auction.ConditionId == 1 && userId == auction.SellerId)
            {
                var model = await auctionService.GetAuctionForEditAsync(id);
                model.Conditions = await auctionService.GetOnlyTwoAuctionConditionsAsync();

                return View(model);
            }
            else if (auction.ConditionId == 2 && User.IsModerator())
            {
                var model = await auctionService.GetAuctionForEditAsync(id);
                model.Conditions = await auctionService.GetAuctionConditionsAsync();

                return View(model);
            }
            else
            {
                return Unauthorized();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, AuctionFormViewModel model)
        {
            if (await auctionService.ExistAsync(id) == false)
            {
                return BadRequest();
            }

            if (await auctionService.ConditionExistAsync(model.ConditionId) == false)
            {
                ModelState.AddModelError(nameof(model.ConditionId), "Condition does not exist");
            }

            if (!ModelState.IsValid)
            {
                model.Conditions = await auctionService.GetAuctionConditionsAsync();
                return View(model);
            }

            var auction = await auctionService.GetAuctionByIdAsync(id);
            var userId = GetUserId();

            if (auction.ConditionId == 1 && userId == auction.SellerId)
            {
                await auctionService.EditAsync(id, model);
            }

            else if (auction.ConditionId == 2 && User.IsModerator())
            {
                await auctionService.EditAsync(id, model);
            }

            return RedirectToAction("MyAuctions", "User");
        }

        private string GetUserId()
        {
            var userId = ClaimsPrincipalExtensions.Id(this.User);

            return userId;
        }
    }
}

AuctionSystem/Controllers/BiddingController.cs
using AuctionSystem.Core.Contracts;
using AuctionSystem.Core.Models.Bidding;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace AuctionSystem.Controllers
{
    public class BiddingController : BaseController
    {
        private readonly IBiddingService biddingService;

        public BiddingController(IBiddingService _biddingService)
        {
            biddingService = _biddingService;
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var model = await biddingService.AllBiddingsAsync();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AllBiddingsForAuction(int id)
        {
            if(await biddingService.AuctionExistAsync(id) == false)
            {
                return BadRequest();
            }

            var model = await biddingService.AllBiddingsForAuctionAsync(id);

            return View("All",model);
        }

        [HttpGet]
        public IActionResult Bidding()
        {
            var model = new BiddingFormViewModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Bidding(BiddingFormViewModel model)
        {
            if (await biddingService.AuctionExistAsync(model.Id) == false)
            {
                ModelState.AddModelError(nameof(model.Id), "Auction does not exist");
            }

            var auction = await biddingService.GetAuctionByIdAsync(model.Id);

            if (!await biddingService.IsActiveAsync(auction.Id))
            {
                TempData["IsActiveMessage"] = "This product is not active";
                return View();
            }

            if (!await biddingService.IsValidAsync(auction.Id))
            {
                TempData["IsActiveMessage"] = "This product is not active";
                return View();
            }

            var minBiddingPrice = auction.LastPrice + auction.MinBiddingStep;

            if (minBiddingPrice > model.LastPrice)
            {
                return View(model);
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var userId = GetUserId();

            await biddingService.AddBiddingAsync(model, userId);
            await biddingService.SetNewValuesForAuctionAsync(model,auction.Id ,userId);

            return RedirectToAction("All", "Auction");
        }

        private string GetUserId()
        {
            var userId = ClaimsPrincipalExtensions.Id(this.User);

            return userId;
        }
    }
}

AuctionSystem/Views/Shared/_AuctionPartial.cshtml
@model AllAuctionViewModel
<div class="col-md-3">
    <div class="card mb-4">
        <div>
            @if (Model.Images != null && Model.Images.Any())
            {
                foreach (var image in Model.Images)
                {
                    if (image.IsMain)
                    {
                        <img src="@image.ImageUrl" alt="Product Image" class="img-thumbnail" style="width: 300px; height: 150px;" />
                    }
                    else
                    {
                        <img src="@image.ImageUrl" alt="Product Image" class="img-thumbnail" style="width: 95px; height: 80px;" />
                    }
                }
            }
        </div>
            <div class="card-body text-center">
                <h5 class="card-title mt-1">@Model.Name</h5>
                <p class="mb-0">Last Price: @Model.LastPrice lv.</p>
                <p class="mb-0">Initial Price: @Model.InitialPrice lv.</p>
                <p class="mb-0">Description: @Model.Description</p>
                <p class="mb-0">Condition: @Model.Condition</p>
                <p class="mb-0">Min bidding step: @Model.MinBiddingStep</p>
                <p class="mb-0">Bidding period in days: @Model.BiddingPeriodInDays</p>
                <a asp-controller="Auction" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Details</a>
            <a asp-controller="AuctionComment" asp-action="Add" asp-route-id="@Model.Id" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Add comment for auction</a>
            <a asp-controller="Bidding" asp-action="Bidding" asp-route-id="@Model.Id" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Bidding</a>
            </div>
    </div>
</div>

AuctionSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Auction System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AuctionSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Auction System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @await Component.InvokeAsync(nameof(MainMenuComponents))
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Today.Year - AuctionSystem
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>