AuctionSystem/Controllers/AuctionController.cs
using AuctionSystem.Core.Contracts;
using AuctionSystem.Core.Models.Auction;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace AuctionSystem.Controllers
{
    public class AuctionController : BaseController
    {
        private readonly IAuctionService auctionService;

        public AuctionController(IAuctionService service)
        {
            auctionService = service;
        }

        [HttpGet]
        public async Task<IActionResult> All([FromQuery] AuctionQueryViewModel model)
        {
            var auctions = await auctionService.AllAuctionAsync(
                model.SearchTerm,
                model.Sorting,
                model.CurrentPage,
                model.AuctionPerPage);

            model.TotalAuctionCount = auctions.TotalAuctionCount;
            model.Auction = auctions.Auction;

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AllAuctionsForUser(string id)
        {
            if (await auctionService.UserExistAsync(id) == false)
            {
                return BadRequest();
            }

            var auctions = await auctionService.GetAllAuctionsForUser(id);

            return View(auctions);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            if (await auctionService.ExistAsync(id) == false)
            {
                return BadRequest();
            }

            var model = await auctionService.DetailsAuctionAsync(id);

            if(model.ConditionId == 4)
            {
                return View(model);
            }
            else
            {
                return BadRequest();
            }
        }
      
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            if(User.IsCustomer() == false)
            {
                return Unauthorized();
            }

            var model = new AuctionFormViewModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AuctionFormViewModel model, List<string> imageUrls)
        {
            if (!User.IsCustomer())
            {
                return Unauthorized();
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            string userId = GetUserId();

            int auctionId =  await auctionService.AddAsync(model, userId);
            var auction = await auctionService.GetAuctionByIdAsync(auctionId);

            await auctionService.AddImagesAsync(auction, model.Image, imageUrls);

            var days = auction.BiddingPeriodInDays;
            var endDate = auction.StartingAuctionDateTime.AddDays(days);

            ScheduleAuctionCompletion(auction.Id, endDate);

            return RedirectToAction(nameof(All));
        }

        private void ScheduleAuctionCompletion(int auctionId, DateTime endDate)
        {
            var delay = endDate - DateTime.Now;

            if (delay <= TimeSpan.Zero)
            {
                Task.Run(() => EndAuctionAfterTimeExpires(auctionId));
            }
            else
            {
                Task.Delay(delay).ContinueWith(_ => EndAuctionAfterTimeExpires(auctionId));
            }
        }
        private async Task EndAuctionAfterTimeExpires(int auctionId)
        {
            await auctionService.SetConditionToFinish(auctionId);
        }
        [HttpGet]
        public async Task<IActionResult> TerminateAuction(int id)
        {
            if (await auctionService.ExistAsync(id) == false)
            {
                return BadRequest();
            }

            var auction = await auctionService.GetAuctionByIdAsync(id);

            if(auction.ConditionId != 4)
            {
                return BadRequest();
            }

            string userId = GetUserId();

            if (User.IsCustomer() && userId == auction.SellerId)
            {
                await auctionService.TerminateAuction(auction.Id);
                return RedirectToAction(nameof(All));
            }
            else
            {
                return Unauthorized();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (await auctionService.ExistAsync(id) == false)
            {
                return BadRequest();
            }

            var auction = await auctionService.GetAuctionByIdAsync(id);
            string userId = GetUserId();

            if (auction.ConditionId == 1 && userId == auction.SellerId)
            {
                var model = await auctionService.GetAuctionForEditAsync(id);
                model.Conditions = await auctionService.GetOnlyTwoAuctionConditionsAsync();

                return View(model);
            }
            else if (auction.ConditionId == 2 && User.IsModerator())
            {
                var model = await auctionService.GetAuctionForEditAsync(id);
                model.Conditions = await auctionService.GetAuctionConditionsAsync();

                return View(model);
            }
            else
            {
                return Unauthorized();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, AuctionFormViewModel model)
        {
            if (await auctionService.ExistAsync(id) == false)
            {
                return BadRequest();
            }

            if (await auctionService.ConditionExistAsync(model.ConditionId) == false)
            {
                ModelState.AddModelError(nameof(model.ConditionId), "Condition does not exist");
            }

            if (!ModelState.IsValid)
            {
                model.Conditions = await auctionService.GetAuctionConditionsAsync();
                return View(model);
            }

            var auction = await auctionService.GetAuctionByIdAsync(id);
            var userId = GetUserId();

            if (auction.ConditionId == 1 && userId == auction.SellerId)
            {
                await auctionService.EditAsync(id, model);
            }

            else if (auction.ConditionId == 2 && User.IsModerator())
            {
                await auctionService.EditAsync(id, model);
            }

            return RedirectToAction("MyAuctions", "User");
        }

        private string GetUserId()
        {
            var userId = ClaimsPrincipalExtensions.Id(this.User);

            return userId;
        }
    }
}

AuctionSystem/Controllers/UserController.cs
using AuctionSystem.Core.Contracts;
using AuctionSystem.Core.Models.User;
using AuctionSystem.Infrastructure.Data.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using static AuctionSystem.Core.Constants.CustomClaim;
using static AuctionSystem.Core.Constants.RoleConstants;

namespace AuctionSystem.Controllers
{
    public class UserController : Controller
    {
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IUserService userService;

        public UserController(SignInManager<ApplicationUser> _signInManager,
            UserManager<ApplicationUser> _userManager,
            IUserStore<ApplicationUser> _userStore,
            IUserService _userService)
        {
            signInManager = _signInManager;
            userManager = _userManager;
            userService = _userService;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterFormModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            ApplicationUser applicationUser = new ApplicationUser()
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                Enable = false
            };

            await userManager.SetEmailAsync(applicationUser, model.Email);
            await userManager.SetUserNameAsync(applicationUser, model.Email);

            var result = await userManager.CreateAsync(applicationUser, model.Password);
            if (!result.Succeeded)
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }

                return View(model);
            }

            await userManager.AddClaimAsync(applicationUser, new System.Security.Claims.Claim(UserFullNameClaim, $"{applicationUser.FirstName} {applicationUser.LastName}"));
            await userManager.AddToRoleAsync(applicationUser, CustomerRole);

            if(applicationUser.Enable == true)
            {
                await signInManager.SignInAsync(applicationUser, false);

                return RedirectToAction("Index", "Home");
            }

            TempData["Message"] = "Wait for admin approval";

            return RedirectToAction(nameof(Login));
        }

        [HttpGet]
        public IActionResult Login(string? returnUrl = null)
        {
            LoginFormModel model = new LoginFormModel()
            {
                ReturnUrl = returnUrl,
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginFormModel model)
        {
            var user = await userManager.FindByEmailAsync(model.Email);

            if (await userService.IsEnableAsync(user.Id) == false)
            {
                TempData["Message"] = "Wait for admin approval";

                return RedirectToAction(nameof(Login));
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var result = await signInManager
                .PasswordSignInAsync(model.Email, model.Password, model.RememberMe, false);
            if (!result.Succeeded)
            {
                ModelState.AddModelError(string.Empty, "There was an error while logging you in! Please try again later or contact an administrator.");

                return View(model);
            }

            return Redirect(model.ReturnUrl ?? "/Home/Index");
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var model = await userService.AllUsersAsync();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            if(await userService.ExistAsync(id) == false)
            {
                return BadRequest();
            }

            var model = await userService.DetailsUsersAsync(id);

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> MyInfo()
        {
            var userId = GetUserId();
            var model = await userService.MyInformationAsync(userId);

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> SellerProfile(int id)
        {
            if(await userService.ExistAuctionAsync(id) == false)
            {
                return BadRequest();
            }

            var model = await userService.SellerProfileAsync(id);

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit()
        {
            var user = await userManager.GetUserAsync(User);

            if(user == null)
            {
                return NotFound();
            }

            var model = new MyInformationViewModel()
            {
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email,
                PhoneNumber = user.PhoneNumber,
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(MyInformationViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await userManager.GetUserAsync(User);

            if(user == null)
            {
                return NotFound();
            }

            await userService.EditAsync(user.Id, model);

            return RedirectToAction(nameof(MyInfo));
        }

        [HttpGet]
        public async Task<IActionResult> MyAuctions()
        {
            string userId = GetUserId();
            var auctions = await userService.GetMyAuctions(userId);

            return View(auctions);
        }

        [HttpGet]
        public async Task<IActionResult> MyAuctionComments()
        {
            string userId = GetUserId();
            var comments = await userService.GetMyAuctionComment(userId);

            return View(comments);
        }

        [HttpGet]
        public async Task<IActionResult> MyUserComments()
        {
            string userId = GetUserId();
            var comments = await userService.GetMyUserComment(userId);

            return View(comments);
        }

        [HttpGet]
        public async Task<IActionResult> MyBiddings()
        {
            string userId = GetUserId();
            var biddings = await userService.GetMyBiddings(userId);

            return View(biddings);
        }

        [HttpGet]
        public async Task<IActionResult> MyWinningAuctions()
        {
            string userId = GetUserId();
            var auctions = await userService.GetMyWinningAuctions(userId);

            return View(auctions);
        }

        private string GetUserId()
        {
            var userId = ClaimsPrincipalExtensions.Id(this.User);

            return userId;
        }
    }
}

AuctionSystem/Areas/Moderator/Views/Shared/_AuctionModeratorPartial.cshtml
@model AllAuctionViewModel

<div class="col-md-3">
    <div class="card mb-4">
        <div>
            @if (Model.Images != null && Model.Images.Any())
            {
                foreach (var image in Model.Images)
                {
                    if (image.IsMain)
                    {
                        <img src="@image.ImageUrl" alt="Product Image" class="img-thumbnail" style="width: 300px; height: 150px;" />
                    }
                    else
                    {
                        <img src="@image.ImageUrl" alt="Product Image" class="img-thumbnail" style="width: 95px; height: 80px;" />
                    }
                }
            }
        </div>
            <div class="card-body text-center">
                <h5 class="card-title mt-1">@Model.Name</h5>
                <p class="mb-0">Last Price: @Model.LastPrice lv.</p>
                <p class="mb-0">Initial Price: @Model.InitialPrice lv.</p>
                <p class="mb-0">Description: @Model.Description</p>
                <p class="mb-0">Condition: @Model.Condition</p>
                <p class="mb-0">Min bidding step: @Model.MinBiddingStep</p>
                <p class="mb-0">Bidding period in days: @Model.BiddingPeriodInDays</p>
              @if (Model.ConditionId == 2 && User.IsModerator())
              {
                <a asp-area="Moderator" asp-controller="Auction" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Edit</a>
            }
            else
            {
                    <a asp-area="Moderator" asp-controller="Auction" asp-action="EditCondition" asp-route-id="@Model.Id" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Edit Condition</a>
            }
            <a asp-area="Moderator" asp-controller="Auction" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Details</a>
            </div>
    </div>
</div>

AuctionSystem/Areas/Moderator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Auction System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AuctionSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Auction System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @await Component.InvokeAsync(nameof(ModeratorMenuComponents))
                    <partial name="_ModeratorPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Today.Year - AuctionSystem <span class="text-danger">This area is only for Moderators!</span>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AuctionSystem/Areas/Moderator/Views/Shared/_ModeratorPartial.cshtml
@using AuctionSystem.Infrastructure.Data.Models;
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<ul class="navbar-nav">
@if (SignInManager.IsSignedIn(User))
{
    <li class="nav-item">
        <a  class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @User.Identity?.Name!</a>
    </li>
    <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index" title="Back">Public Interface</a>
    </li>
}
else
{
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Register">Register</a>
        </li>
        <li class ="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Login</a>
        </li>
}
</ul>