AuctionSystem/Areas/Administrator/Controllers/UserCommentController.cs
using AuctionSystem.Core.Contracts;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace AuctionSystem.Areas.Administrator.Controllers
{
    public class UserCommentController : AdministartorBaseController
    {
        private readonly IUserCommentService userCommentService;

        public UserCommentController(IUserCommentService _userCommentService)
        {
            userCommentService = _userCommentService;
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var model = await userCommentService.AllCommentsAsync();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (await userCommentService.ExistAsync(id) == false)
            {
                return BadRequest();
            }

            if (User.IsModerator() == false && User.IsAdmin() == false)
            {
                return Unauthorized();
            }

            var model = await userCommentService.GetUserCommentForDeleteAsync(id);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (await userCommentService.ExistAsync(id) == false)
            {
                return BadRequest();
            }

            if (User.IsModerator() == false && User.IsAdmin() == false)
            {
                return Unauthorized();
            }

            await userCommentService.RemoveAsync(id);

            return RedirectToAction(nameof(All));
        }
    }
}

AuctionSystem/Areas/Moderator/Controllers/UserCommentController.cs
using AuctionSystem.Core.Contracts;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace AuctionSystem.Areas.Moderator.Controllers
{
    public class UserCommentController : ModeratorBaseController
    {
        private readonly IUserCommentService userCommentService;

        public UserCommentController(IUserCommentService _userCommentService)
        {
            userCommentService = _userCommentService;
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var model = await userCommentService.AllCommentsAsync();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (await userCommentService.ExistAsync(id) == false)
            {
                return BadRequest();
            }

            if (User.IsModerator() == false && User.IsAdmin() == false)
            {
                return Unauthorized();
            }

            var model = await userCommentService.GetUserCommentForDeleteAsync(id);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (await userCommentService.ExistAsync(id) == false)
            {
                return BadRequest();
            }

            if (User.IsModerator() == false && User.IsAdmin() == false)
            {
                return Unauthorized();
            }

            await userCommentService.RemoveAsync(id);

            return RedirectToAction(nameof(All));
        }
    }
}

AuctionSystem/Controllers/UserCommentController.cs
using AuctionSystem.Core.Contracts;
using AuctionSystem.Core.Models.UserComment;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace AuctionSystem.Controllers
{
    public class UserCommentController : Controller
    {
        private readonly IUserCommentService userCommentService;

        public UserCommentController(IUserCommentService _userCommentService)
        {
            userCommentService = _userCommentService;
        }

        [HttpGet]
        public async Task<IActionResult> AllCommentAboutUserFromOtherUsers(string id)
        {
            if(await userCommentService.UserExistAsync(id) == false)
            {
                return BadRequest();
            }

            var comments = await userCommentService.GetAllCommentAboutUserFromOtherUsers(id);

            return View(comments);
        }

        [HttpGet]
        public async Task<IActionResult> AllUserCommentsForOtherUsers(string id)
        {
            if (await userCommentService.UserExistAsync(id) == false)
            {
                return BadRequest();
            }

            var comments = await userCommentService.GetAllUserCommentsForOtherUsers(id);

            return View(comments);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var model = new UserCommentFormViewModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(UserCommentFormViewModel model)
        {
            if (await userCommentService.UserExistAsync(model.Id) == false)
            {
                ModelState.AddModelError(nameof(model.Id), "User does not exist");
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var userId = GetUserId();
            await userCommentService.AddAsync(model, userId);

            return RedirectToAction("All","User");
        }

        private string GetUserId()
        {
            var userId = ClaimsPrincipalExtensions.Id(this.User);

            return userId;
        }
    }
}

AuctionSystem/Areas/Moderator/Views/UserComment/All.cshtml
@model IEnumerable<AllUserCommentsViewModel>
@{
    ViewBag.Title = "All User Comments";
}

<style>
    .card-body {
        font-size: 1.1em;
        font-weight: bold;
    }
</style>

<h2 class="text-center">@ViewBag.Title</h2>
<hr />
<div class="text-center row flex gap-4 m-4 justify-content-center">
    @foreach (var c in Model)
    {
        <div class="card col-4" style="width: 20rem; ">
            <div class="card-body">
                <p class="card-title mt-1">Comment: @c.Content</p>
                <p class="mb-0">Receiving Comment User: @c.ReceivingCommentUserName</p>
                <p class="mb-0">Sending Comment User: @c.SendingCommentUserName</p>
            </div>
            <a asp-area="Moderator" asp-controller="UserComment" asp-action="Delete" asp-route-id="@c.Id" class="btn btn-danger mb-2 w-100 p-3 fw-bold">Delete</a>
        </div>
    }
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

AuctionSystem/Areas/Moderator/Views/UserComment/Delete.cshtml
@model DeleteUserCommentViewModel
@{
    ViewBag.Title = "Delete User Comment";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />
<div class="row justify-content-center">
    <div class="col-md-4">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title text-center">Comment: @Model.Content</h3>
                <h4 class="card-title text-center">Sending Comment User: @Model.SendingCommentUserName</h4>
                <p class="text-danger mt-3">"Are you sure you want to delete this user comment?"</p>
            </div>
            <div class="card-footer">
                <form asp-action="DeleteConfirmed" method="post">
                    <input type="hidden" asp-for="Id" />
                    <button type="submit" class="btn btn-danger">Confirm Delete</button>
                    <a asp-action="All" class="btn btn-secondary">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>